apiVersion: v2
name: t8s-cluster
type: application
version: 0.0.1
icon: https://teuto.net/favicon.ico
maintainers:
  - name: cwrau
    email: cwr@teuto.net
  - name: marvinWolff
    email: mw@teuto.net
sources:
  - https://github.com/teutonet/teutonet-helm-charts
home: https://teuto.net
description: t8s-operator cluster with necessary addons
dependencies:
  - name: common
    version: 2.2.3
    repository: https://charts.bitnami.com/bitnami
annotations:
  artifacthub.io/images: |
    - image: quay.io/cilium/cilium:v1.12.7@sha256:8cb6b4742cc27b39e4f789d282a1fc2041decb6f5698bfe09112085a07b1fd61
    - image: quay.io/cilium/hubble-relay:v1.12.7@sha256:edf491e362b52e2b5461b2bff346a79c76365c9595b675146edd01f9c28ae942
    - image: quay.io/cilium/hubble-ui-backend:v0.9.2@sha256:a3ac4d5b87889c9f7cc6323e86d3126b0d382933bd64f44382a92778b0cde5d7
    - image: quay.io/cilium/hubble-ui:v0.9.2@sha256:d3596efc94a41c6b772b9afe6fe47c17417658956e04c3e2a28d293f2670663e
    - image: quay.io/cilium/operator-generic:v1.12.7@sha256:80f24810bf8484974c757382eb2c7408c9c024e5cb0719f4a56fba3f47695c72
    - image: registry.k8s.io/etcd:3.5.6-0
