name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**
  workflow_dispatch: {}

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.ORIGAMI_GITHUB_TOKEN }}
          command: release-pr
          monorepo-tags: true
  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.releases_created
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.5.2

      - name: install yq
        run: |
          sudo snap install yq

      - name: Extract and add helm repos
        id: helm-repos
        run: |
          for DIR in ./charts/*; do
            FILE="$DIR/Chart.yaml"
            DIR="${DIR//\./}"
            yq e '.dependencies.[].repository' "$FILE"
          done | sort -u | awk '{print NR " " $1}' | xargs -r -n 2 helm repo add

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
