name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - charts/**
  workflow_dispatch: {}

jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      changedCharts: ${{ steps.getChangedCharts.outputs.changedCharts }}
    steps:
      - id: latestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: ${{ github.repository }}
        continue-on-error: true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
      - id: getChangedCharts
        run: |
          set -x
          set -o pipefail
          LATEST_RELEASE="${{ steps.latestRelease.release }}"
          LATEST_RELEASE="${LATEST_RELEASE:-$(git rev-list HEAD | tail -n 1)}"
          (
            echo -n changedCharts=
            ct list-changed --target-branch main --since "$LATEST_RELEASE" | cut -d / -f 2 | jq -c -Rn '[inputs]'
          ) | tee $GITHUB_OUTPUT
  release-please-release:
    runs-on: ubuntu-latest
    needs:
      - changeFinder
    strategy:
      fail-fast: false
      matrix:
        chart: ${{fromJson(needs.changeFinder.outputs.changedCharts)}}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          path: charts/${{ matrix.chart }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: helm
          monorepo-tags: true
          package-name: ${{ matrix.chart }}
          command: release-pr
